web:
    port: 8084
cctv:
    nvr_ip: 192.168.0.200
    nvr_port: 40000
dstore:
    servermain_port: 1719
    serversecond_port: 1720
    serveraux_port: 1721
vbspos:
    multicast_ip: 230.0.0.1
    vbspos_port: 4050
license:
    machine_fingerprint: f0:d4:15:05:36:e2
    unlock_key: Y9zMRazRpWOU9aUnf3rTMhTB2qy3s0PKW5St/eqGPrk=
ipmaps:
    - ipaddress: 192.168.1.101
      port: 55000
      type: 6
    - ipaddress: 192.168.1.102
      port: 55000
      type: 6
    - ipaddress: 192.168.1.103
      port: 55000
      type: 6
    - ipaddress: 192.168.1.104
      port: 55000
      type: 6
    - ipaddress: 192.168.1.105
      port: 55000
      type: 6
    - ipaddress: 192.168.1.106
      port: 55000
      type: 5
    - ipaddress: 192.168.1.107
      port: 55000
      type: 5
    - ipaddress: 192.168.1.108
      port: 55000
      type: 5
    - ipaddress: 192.168.1.109
      port: 41001
      type: 5
    - ipaddress: 192.168.1.110
      port: 41001
      type: 1
    - ipaddress: 192.168.1.111
      port: 41001
      type: 1
    - ipaddress: 192.168.1.112
      port: 41001
      type: 1
    - ipaddress: 192.168.0.20
      port: 40001
      type: 1
device_types:
    - id: 1
      name: Terioka
      description: UDP Protocol
    - id: 2
      name: Terioka
      description: SM110 TCP Protocol
    - id: 3
      name: Terioka
      description: SM120 TCP Protocol
    - id: 4
      name: Terioka
      description: SM5000 TCP Protocol
    - id: 5
      name: Ishida
      description: UNI Protocol
    - id: 6
      name: Ishida
      description: BC4000 Protocol
site_details:
    site_name: UltechHQ
    branch: East London
    site_location: Beaconbay
    owner_name: Trevor
    owner_surname: Pomfret
    contact_cell: "0836565995"
    contact_email: trevor@ultech.co.za
admin:
    username: admin
    password: admin
