# configs/default.yaml
web:
  port: 8081

cctv:
  nvr_ip: "192.168.1.50"
  nvr_port: 14000

license:
  max_total_devices: 50
  max_per_scale: 64
  machine_fingerprint: "f0:d4:15:05:36:e2"  # replace with real MAC